import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, Check, Mail, MapPin, Phone, Play } from "lucide-react";
import { Link, useRoute } from "wouter";
import { catalogue, PageShell, SiteFooter, SiteHeader } from "./Products";
import type { BlogPost } from "@shared/lead-desk";

const sectorCards = [
  { title: "Clinics & medical", label: "Clinical environments", body: "Specify premium recovery systems around patient experience, protocols, and operator confidence.", image: "/manus-storage/hyperbaric-room_f8b7624d.webp", points: ["Clinical-grade capability", "Site planning support", "Commissioning and training"] },
  { title: "Gyms & performance", label: "Performance environments", body: "Turn recovery into a visible, valuable part of the member experience with the right equipment circuit.", image: "/manus-storage/cryotherapy-gym_647bf934.jpg", points: ["High-throughput systems", "Member experience design", "Equipment mix guidance"] },
  { title: "Hotels & hospitality", label: "Guest wellness", body: "Create a differentiated wellness destination with a considered equipment mix and a calm spatial experience.", image: "/manus-storage/wellness-club_26daad98.jpg", points: ["Guest-facing environments", "Premium positioning", "Project coordination"] },
  { title: "Private / residential", label: "Personal sanctuaries", body: "Bring world-class recovery into the home with discreet, thoughtful integration and specialist guidance.", image: "/manus-storage/red-light-room_6bd1bed1.jpg", points: ["Private wellness rooms", "Space-led specification", "White-glove support"] },
];

export function Sectors() {
  return <PageShell eyebrow="Sectors / Environments" title={<>Designed around<br /><em>your ambition.</em></>} intro="The right equipment looks different in a clinic, a performance club, a hotel, and a private residence. Start with the environment you are building." breadcrumb="Sectors"><div className="grid gap-5 md:grid-cols-2">{sectorCards.map((sector, index) => <Link href="/contact" key={sector.title} className="group relative min-h-[480px] overflow-hidden"><img src={sector.image} alt={sector.title} className="absolute inset-0 h-full w-full object-cover grayscale transition duration-500 group-hover:scale-105 group-hover:grayscale-0" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/15 to-transparent" /><div className="absolute inset-x-6 bottom-6 text-white"><div className="text-[10px] uppercase tracking-[0.22em] text-[#d5c59d]">{String(index + 1).padStart(2, "0")} / {sector.label}</div><h2 className="mt-3 font-serif text-4xl">{sector.title}</h2><p className="mt-3 max-w-[430px] text-sm leading-6 text-white/70">{sector.body}</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-[10px] uppercase tracking-[0.13em] text-white/75">{sector.points.map((point) => <span key={point} className="flex items-center gap-2"><Check size={12} className="text-[#d5c59d]" />{point}</span>)}</div><span className="mt-7 inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.18em]">Explore this environment <ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></div></Link>)}</div></PageShell>;
}

const posts = [
  { slug: "how-to-specify-a-recovery-room", category: "Buying guide", title: "How to specify a recovery room that performs", excerpt: "The practical questions to ask before choosing equipment, planning a footprint, or building an operating model.", date: "08 Sep 2026", image: "/manus-storage/hyperbaric-room_f8b7624d.webp", featured: true },
  { slug: "understanding-hyperbaric-oxygen-environments", category: "Science", title: "Understanding hyperbaric oxygen environments", excerpt: "A clear introduction to chamber formats, pressure, and the role of clinical oversight.", date: "28 Aug 2026", image: "/manus-storage/cryotherapy-gym_647bf934.jpg" },
  { slug: "the-new-language-of-recovery-interiors", category: "Design & space", title: "The new language of recovery interiors", excerpt: "Why the best wellness spaces feel less like equipment rooms and more like destinations.", date: "14 Aug 2026", image: "/manus-storage/wellness-club_26daad98.jpg" },
  { slug: "from-delivery-to-daily-confidence", category: "Operator guide", title: "From delivery to daily confidence", excerpt: "What commissioning, training, and service support should look like after installation.", date: "02 Aug 2026", image: "/manus-storage/red-light-room_6bd1bed1.jpg" },
];

export function Blogs() {
  const [managedPosts, setManagedPosts] = useState<typeof posts>(posts);
  useEffect(() => { fetch("/api/posts/published").then((response) => response.ok ? response.json() : Promise.reject()).then((data: { posts: BlogPost[] }) => setManagedPosts(data.posts.map((post, index) => ({ ...post, featured: index === 0 })))).catch(() => undefined); }, []);
  return <PageShell eyebrow="Science & journal" title={<>Ideas for a<br /><em>healthier future.</em></>} intro="Practical guidance, science-led explainers, and the thinking behind the spaces where recovery happens." breadcrumb="Journal"><div className="grid gap-x-6 gap-y-12 md:grid-cols-2">{managedPosts.map((post) => <article key={post.title} className={post.featured ? "md:col-span-2" : ""}><Link href={`/blogs/${post.slug}`} className={`group grid gap-7 ${post.featured ? "lg:grid-cols-[1.25fr_.75fr] lg:items-center" : ""}`}><div className={`overflow-hidden bg-[#ded8cc] ${post.featured ? "aspect-[1.5]" : "aspect-[1.22]"}`}><img src={post.image} alt="" className="h-full w-full object-cover mix-blend-multiply transition duration-500 group-hover:scale-105 group-hover:mix-blend-normal" /></div><div><div className="text-[10px] uppercase tracking-[0.2em] text-[#9d8251]">{post.category} · {post.date}</div><h2 className={`mt-3 font-serif leading-[.95] ${post.featured ? "text-5xl lg:text-6xl" : "text-3xl"}`}>{post.title}</h2><p className="mt-4 max-w-[430px] text-sm leading-6 text-[#6f6a61]">{post.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.18em]">Read article <ArrowUpRight size={14} /></span></div></Link></article>)}</div></PageShell>;
}

export function DynamicBlogDetail() {
  const [, params] = useRoute<{ slug: string }>("/blogs/:slug");
  const [post, setPost] = useState<BlogPost | null>(null);
  useEffect(() => { if (params?.slug) fetch(`/api/posts/published/${params.slug}`).then((response) => response.ok ? response.json() : Promise.reject()).then(setPost).catch(() => setPost(null)); }, [params?.slug]);
  if (!post) return <PageShell eyebrow="Journal" title={<>Article<br /><em>not found.</em></>} intro="This article may have moved or is not published yet." breadcrumb="Journal"><div /></PageShell>;
  return <PageShell eyebrow={`${post.category} / ${post.date}`} title={<>{post.title}</>} intro={post.excerpt} breadcrumb="Journal / Article"><article className="mx-auto max-w-[940px]"><img src={post.image} alt={post.title} className="aspect-[1.8] w-full object-cover" /><div className="mx-auto max-w-[700px] whitespace-pre-wrap py-12 text-sm leading-7 text-[#5f5b53]">{post.body || post.excerpt}</div></article></PageShell>;
}

export function BlogDetail() {
  return <PageShell eyebrow="Buying guide / 08 Sep 2026" title={<>How to specify a<br /><em>recovery room.</em></>} intro="The practical questions to ask before choosing equipment, planning a footprint, or building an operating model." breadcrumb="Journal / Article"><article className="mx-auto max-w-[940px]"><img src="/manus-storage/hyperbaric-room_f8b7624d.webp" alt="Premium recovery room" className="aspect-[1.8] w-full object-cover" /><div className="mx-auto max-w-[700px] py-12"><p className="font-serif text-3xl leading-tight">A recovery room is not defined by the number of machines in it. It is defined by the quality of the journey those machines create.</p><div className="mt-10 space-y-7 text-sm leading-7 text-[#5f5b53]"><p>Before comparing equipment, start with the people who will use the space and the protocols it needs to support. A clinic may prioritise clinical supervision, privacy, and operator flow. A performance club may prioritise throughput, visibility, and the way recovery becomes part of the membership experience.</p><h2 className="font-serif text-4xl leading-none text-[#191918]">Begin with the environment</h2><p>Document the available footprint, power, ventilation, access route, staffing model, and intended daily use. The best specification is the one that works operationally, not only on paper.</p><h2 className="font-serif text-4xl leading-none text-[#191918]">Then build the circuit</h2><p>Hyperbaric oxygen, cryotherapy, photobiomodulation, cold plunge, and compression each play a different role in a considered recovery journey. Start with the desired experience, then select the modalities that make the most sense together.</p><blockquote className="border-l-2 border-[#bca477] pl-5 font-serif text-2xl italic text-[#302d27]">The most valuable system is the one your team can operate confidently and your client can understand immediately.</blockquote><p>AAAYAN helps teams move from equipment selection to a complete operating environment with site guidance, installation, commissioning, and ongoing support.</p></div><Link href="/contact" className="mt-10 inline-flex items-center gap-3 border-b border-[#24231f] pb-2 text-[10px] uppercase tracking-[0.18em]">Talk to a specialist <ArrowRight size={14} /></Link></div></article></PageShell>;
}

export function Support() { return <PageShell eyebrow="Support / Long-term confidence" title={<>Good equipment<br /><em>needs good support.</em></>} intro="From site survey to commissioning, training, and ongoing service, the AAAYAN team stays close to the project after the purchase." breadcrumb="Support"><div className="grid gap-6 md:grid-cols-2">{[{ title: "Site survey & planning", body: "Understand the room, route, utilities, and operating model before you specify." }, { title: "Installation & commissioning", body: "Bring the system online with a considered installation and clear handover." }, { title: "Operator training", body: "Give your team the knowledge and confidence to deliver a consistent experience." }, { title: "Service & maintenance", body: "Keep your investment performing with responsive technical support and service planning." }].map((item, index) => <div key={item.title} className="border-t border-[#1d1d1b]/20 pt-5"><div className="flex justify-between text-[10px] uppercase tracking-[0.2em] text-[#9d8251]"><span>0{index + 1}</span><ArrowRight size={14} /></div><h2 className="mt-12 font-serif text-4xl">{item.title}</h2><p className="mt-4 max-w-[380px] text-sm leading-6 text-[#6f6a61]">{item.body}</p></div>)}</div><div className="mt-20 bg-[#20201e] p-8 text-white lg:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="text-[10px] uppercase tracking-[0.22em] text-[#d5c59d]">Need a service conversation?</div><h2 className="mt-3 font-serif text-5xl">Let’s keep it performing.</h2></div><Link href="/contact" className="inline-flex items-center gap-3 bg-[#d5c59d] px-5 py-3.5 text-[10px] uppercase tracking-[0.18em] text-[#1c1b18]">Contact support <ArrowRight size={14} /></Link></div></div></PageShell>; }

export function Contact() { return <div className="min-h-screen bg-[#f4f1ea] text-[#191918]"><SiteHeader /><main className="mx-auto grid max-w-[1440px] gap-14 px-5 pb-24 pt-36 lg:grid-cols-[.75fr_1.25fr] lg:px-16"><div><div className="text-[10px] uppercase tracking-[0.28em] text-[#8a7657]">Start a conversation</div><h1 className="mt-5 font-serif text-[clamp(3rem,6vw,6rem)] leading-[.88]">Find your<br /><em>fit.</em></h1><p className="mt-8 max-w-[410px] text-sm leading-7 text-[#5f5b53]">Tell us about your space, your goals, and the systems you are considering. We will help you make the next decision.</p><div className="mt-12 space-y-5 text-sm text-[#5f5b53]"><div className="flex items-center gap-3"><Mail size={17} className="text-[#9d8251]" />info@aaayanimmunotech.co.in</div><div className="flex items-center gap-3"><Phone size={17} className="text-[#9d8251]" />+91 98765 43210</div><div className="flex items-center gap-3"><MapPin size={17} className="text-[#9d8251]" />New Delhi · India</div></div></div><form onSubmit={(event) => { event.preventDefault(); alert("Thank you. A specialist will be in touch shortly."); }} className="bg-[#e9e4da] p-6 sm:p-10"><div className="grid gap-6 sm:grid-cols-2"><label className="text-[10px] uppercase tracking-[0.16em] text-[#6f6a61]">Name<input required className="mt-3 w-full border-b border-[#1d1d1b]/20 bg-transparent py-3 text-sm outline-none" placeholder="Full name" /></label><label className="text-[10px] uppercase tracking-[0.16em] text-[#6f6a61]">Work email<input required type="email" className="mt-3 w-full border-b border-[#1d1d1b]/20 bg-transparent py-3 text-sm outline-none" placeholder="you@company.com" /></label></div><label className="mt-7 block text-[10px] uppercase tracking-[0.16em] text-[#6f6a61]">I am building<select className="mt-3 w-full border-b border-[#1d1d1b]/20 bg-transparent py-3 text-sm outline-none"><option>Clinic or medical facility</option><option>Gym or performance club</option><option>Hotel or hospitality space</option><option>Private / residential space</option></select></label><label className="mt-7 block text-[10px] uppercase tracking-[0.16em] text-[#6f6a61]">Tell us about the requirement<textarea className="mt-3 min-h-[150px] w-full resize-none border-b border-[#1d1d1b]/20 bg-transparent py-3 text-sm outline-none" placeholder="Equipment, city, space, timeline..." /></label><button className="mt-8 inline-flex items-center gap-3 bg-[#24231f] px-5 py-4 text-[10px] uppercase tracking-[0.18em] text-white">Send enquiry <ArrowRight size={14} /></button></form></main><SiteFooter /></div>; }

export function ProductDetail() {
  const [, params] = useRoute<{ id: string }>("/products/:id");
  const product = catalogue.find((item) => item.id === params?.id) || catalogue[0];
  return <div className="min-h-screen bg-[#f4f1ea] text-[#191918]"><SiteHeader /><main className="mx-auto max-w-[1440px] px-5 pb-24 pt-32 lg:px-16"><div className="mb-8 flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-[#8a7657]"><Link href="/products">Products</Link><span>/</span><span>{product.category}</span></div><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="aspect-square overflow-hidden bg-[#ded8cc]"><img src={product.image} alt={product.name} className="h-full w-full object-cover mix-blend-multiply" /></div><div><div className="text-[10px] uppercase tracking-[0.22em] text-[#9d8251]">{product.eyebrow}</div><h1 className="mt-4 font-serif text-[clamp(3rem,6vw,6.5rem)] leading-[.87]">{product.name}</h1><p className="mt-7 max-w-[500px] text-sm leading-7 text-[#5f5b53]">{product.description}</p><div className="mt-8 grid grid-cols-2 gap-4 border-y border-[#1d1d1b]/15 py-5"><div><div className="text-[9px] uppercase tracking-[0.16em] text-[#8a7657]">Specification</div><div className="mt-2 text-sm">{product.spec}</div></div><div><div className="text-[9px] uppercase tracking-[0.16em] text-[#8a7657]">Commercial model</div><div className="mt-2 text-sm">Project quotation</div></div></div><div className="mt-8 space-y-3">{product.details.map((detail) => <div key={detail} className="flex items-center gap-3 text-sm text-[#5f5b53]"><Check size={15} className="text-[#9d8251]" />{detail}</div>)}</div><Link href="/contact" className="mt-10 inline-flex items-center gap-3 bg-[#24231f] px-5 py-4 text-[10px] uppercase tracking-[0.18em] text-white">Request product consultation <ArrowRight size={14} /></Link></div></div><div className="mt-24 grid gap-8 border-t border-[#1d1d1b]/15 pt-10 md:grid-cols-3">{[{ title: "Specify", body: "Share your space, goals, and operating model." }, { title: "Deploy", body: "Receive a considered quote and implementation plan." }, { title: "Support", body: "Get training, service, and long-term confidence." }].map((item, index) => <div key={item.title}><div className="text-[10px] uppercase tracking-[0.18em] text-[#9d8251]">0{index + 1}</div><h2 className="mt-4 font-serif text-3xl">{item.title}</h2><p className="mt-3 text-sm leading-6 text-[#6f6a61]">{item.body}</p></div>)}</div></main><SiteFooter /></div>;
}
