import { useMemo, useState } from "react";
import { ArrowRight, Check, Search, ShoppingBag } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

export type CatalogueProduct = {
  id: string;
  name: string;
  eyebrow: string;
  category: string;
  price: string;
  description: string;
  image: string;
  spec: string;
  badge?: string;
  details: string[];
};

export const catalogue: CatalogueProduct[] = [
  { id: "aether-hbot", name: "Aether HBOT 3.0", eyebrow: "Clinical recovery", category: "Hyperbaric", price: "On consultation", description: "A premium monoplace hyperbaric system engineered for clinical-grade recovery environments.", image: "/manus-storage/hyperbaric-room_f8b7624d.webp", spec: "Up to 3 ATA", badge: "Best seller", details: ["Monoplace hyperbaric chamber", "Up to 3 ATA operating pressure", "Designed for clinical and premium wellness spaces", "Site planning and operator training available"] },
  { id: "nordik-chamber", name: "NØRDIK Chamber", eyebrow: "Whole-body recovery", category: "Cryotherapy", price: "On consultation", description: "A sculptural whole-body cryotherapy experience built for high-throughput performance spaces.", image: "/manus-storage/cryotherapy-gym_647bf934.jpg", spec: "Electric / nitrogen-free", details: ["Whole-body cryotherapy system", "Electric, nitrogen-free operation", "Built for gyms and performance clubs", "Commissioning and support available"] },
  { id: "luma-850", name: "Luma 850 Bed", eyebrow: "Photobiomodulation", category: "Red light / PBM", price: "On consultation", description: "Full-body red light therapy with a considered footprint for premium recovery and wellness suites.", image: "/manus-storage/red-light-room_6bd1bed1.jpg", spec: "660nm + 850nm", badge: "New arrival", details: ["Full-body photobiomodulation bed", "660nm and 850nm wavelength architecture", "Suitable for recovery and wellness suites", "Space planning guidance available"] },
  { id: "mizu-plunge", name: "Mizu Cold Plunge", eyebrow: "Contrast therapy", category: "Cold plunge", price: "On consultation", description: "A commercial-grade cold plunge with a calm, architectural silhouette for hospitality and performance use.", image: "/manus-storage/wellness-club_26daad98.jpg", spec: "Commercial capacity", details: ["Commercial cold plunge station", "Designed for repeated daily use", "Suitable for hospitality and performance spaces", "Installation requirements supplied"] },
  { id: "velo-compression", name: "Velo Compression System", eyebrow: "Active recovery", category: "Compression", price: "On consultation", description: "A fast, intuitive compression station designed to complete a premium recovery circuit.", image: "/manus-storage/wellness-club_26daad98.jpg", spec: "Multi-zone control", details: ["Multi-zone compression control", "Compact footprint for recovery circuits", "Fast operator handover", "Ideal complement to larger recovery systems"] },
];

const categories = ["All equipment", "Hyperbaric", "Cryotherapy", "Red light / PBM", "Cold plunge", "Compression"];

export default function Products() {
  const [active, setActive] = useState("All equipment");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const filtered = useMemo(() => catalogue.filter((product) => (active === "All equipment" || product.category === active) && (!query || `${product.name} ${product.category} ${product.description}`.toLowerCase().includes(query.toLowerCase()))), [active, query]);

  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length >= 3 ? [...current.slice(1), id] : [...current, id]);

  return <PageShell eyebrow="Equipment / Collection" title={<>World-class technology.<br /><em>Real-world results.</em></>} intro="Explore the recovery systems that anchor premium clinical, performance, hospitality, and private wellness environments." breadcrumb="Products">
    <div className="flex flex-col justify-between gap-5 border-y border-[#1d1d1b]/15 py-5 lg:flex-row lg:items-center"><div className="flex gap-2 overflow-x-auto scrollbar-none">{categories.map((category) => <button key={category} onClick={() => setActive(category)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-[10px] uppercase tracking-[0.14em] ${active === category ? "border-[#24231f] bg-[#24231f] text-white" : "border-[#1d1d1b]/15 text-[#6f6a61]"}`}>{category}</button>)}</div><div className="flex items-center gap-2 border-b border-[#1d1d1b]/20 pb-2 text-sm text-[#5f5b53] lg:w-[250px]"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search equipment" className="w-full bg-transparent outline-none placeholder:text-[#8c887f]" /></div></div>
    <div className="mt-12 grid gap-x-6 gap-y-14 md:grid-cols-2 xl:grid-cols-3">{filtered.map((product, index) => <article key={product.id} className="group"><div className="relative aspect-[1.08] overflow-hidden bg-[#ded8cc]"><img src={product.image} alt={product.name} className="h-full w-full object-cover mix-blend-multiply transition duration-500 group-hover:scale-105 group-hover:mix-blend-normal" /><div className="absolute inset-0 bg-gradient-to-t from-black/35 to-transparent" /><div className="absolute inset-x-4 top-4 flex justify-between"><span className="rounded-full bg-[#f4f1ea]/90 px-2.5 py-1 text-[9px] uppercase tracking-[0.15em]">{String(index + 1).padStart(2, "0")}</span>{product.badge && <span className="rounded-full bg-[#d5c59d] px-2.5 py-1 text-[9px] uppercase tracking-[0.14em]">{product.badge}</span>}</div><button onClick={() => toggle(product.id)} className={`absolute bottom-4 right-4 flex items-center gap-2 rounded-full px-3 py-2 text-[9px] uppercase tracking-[0.12em] ${selected.includes(product.id) ? "bg-[#d5c59d] text-[#1c1b18]" : "bg-[#191918]/75 text-white"}`}>{selected.includes(product.id) ? <Check size={13} /> : <ShoppingBag size={13} />} {selected.includes(product.id) ? "Selected" : "Shortlist"}</button></div><div className="pt-5"><div className="text-[9px] uppercase tracking-[0.2em] text-[#9d8251]">{product.eyebrow}</div><div className="mt-2 flex items-start justify-between gap-3"><h2 className="font-serif text-[29px] leading-none">{product.name}</h2><span className="pt-1 text-[9px] uppercase tracking-[0.12em] text-[#777067]">{product.spec}</span></div><p className="mt-4 text-xs leading-5 text-[#6f6a61]">{product.description}</p><div className="mt-5 flex items-center justify-between border-t border-[#1d1d1b]/12 pt-4"><span className="text-[10px] uppercase tracking-[0.13em] text-[#777067]">{product.price}</span><Link href={`/products/${product.id}`} className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.15em]">View product <ArrowRight size={14} /></Link></div></div></article>)}</div>
    {selected.length > 0 && <div className="mt-14 flex flex-col items-start justify-between gap-4 border border-[#1d1d1b]/15 bg-[#e9e4da] p-5 sm:flex-row sm:items-center"><div><div className="text-[10px] uppercase tracking-[0.16em]">{selected.length} system{selected.length > 1 ? "s" : ""} shortlisted</div><div className="mt-1 text-xs text-[#6f6a61]">Use your shortlist for a focused consultation.</div></div><button onClick={() => toast("Shortlist ready", { description: "A specialist will help you compare these systems." })} className="inline-flex items-center gap-2 bg-[#24231f] px-4 py-3 text-[10px] uppercase tracking-[0.16em] text-white">Compare shortlist <ArrowRight size={14} /></button></div>}
  </PageShell>;
}

export function PageShell({ eyebrow, title, intro, breadcrumb, children }: { eyebrow: string; title: React.ReactNode; intro: string; breadcrumb?: string; children: React.ReactNode }) {
  return <div className="min-h-screen bg-[#f4f1ea] text-[#191918]"><SiteHeader /><main className="pt-28"><section className="mx-auto max-w-[1440px] px-5 pb-16 lg:px-16 lg:pb-24"><div className="mb-8 flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-[#8a7657]"><Link href="/">Home</Link><span>/</span><span>{breadcrumb || eyebrow}</span></div><div className="grid gap-8 border-b border-[#1d1d1b]/15 pb-12 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><div className="mb-4 text-[10px] uppercase tracking-[0.28em] text-[#8a7657]">{eyebrow}</div><h1 className="font-serif text-[clamp(3rem,6vw,6.8rem)] leading-[.88] tracking-[-0.045em]">{title}</h1></div><p className="max-w-[470px] text-sm leading-7 text-[#5f5b53] lg:justify-self-end">{intro}</p></div></section><div className="mx-auto max-w-[1440px] px-5 pb-24 lg:px-16">{children}</div></main><SiteFooter /></div>;
}

export function SiteHeader() {
  return <header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#161615]/95 text-[#f8f5ee] backdrop-blur-xl"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#b7a77e]/60 text-[10px] tracking-[0.24em] text-[#d4c39b]">AA</span><span className="leading-none"><span className="block font-serif text-[18px] tracking-[0.16em]">AAAYAN</span><span className="mt-1 block text-[8px] uppercase tracking-[0.36em] text-white/55">Immunotech</span></span></Link><nav className="hidden items-center gap-7 text-[10px] uppercase tracking-[0.2em] text-white/65 lg:flex"><Link href="/products" className="hover:text-white">Shop equipment</Link><Link href="/sectors" className="hover:text-white">Sectors</Link><Link href="/blogs" className="hover:text-white">Science & journal</Link><Link href="/support" className="hover:text-white">Support</Link></nav><Link href="/contact" className="border border-[#d5c59d]/70 px-4 py-2.5 text-[10px] uppercase tracking-[0.18em] text-[#f4e8c7]">Request a quote</Link></div></header>;
}

export function SiteFooter() { return <footer className="bg-[#f4f1ea] px-5 py-12 lg:px-16"><div className="mx-auto flex max-w-[1440px] flex-col gap-9 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/" className="font-serif text-2xl tracking-[0.16em]">AAAYAN</Link><div className="mt-2 text-[9px] uppercase tracking-[0.3em] text-[#7f786d]">Immunotech / Recovery infrastructure</div></div><div className="flex flex-wrap gap-x-7 gap-y-3 text-[10px] uppercase tracking-[0.16em] text-[#6f6a61]"><Link href="/products">Products</Link><Link href="/sectors">Sectors</Link><Link href="/blogs">Journal</Link><Link href="/support">Support</Link><Link href="/contact">Contact</Link></div><div className="text-right text-[10px] leading-5 text-[#8c887f]"><div>info@aaayanimmunotech.co.in</div><div>New Delhi · India</div></div></div><div className="mx-auto mt-10 flex max-w-[1440px] justify-between border-t border-[#1d1d1b]/10 pt-5 text-[9px] uppercase tracking-[0.15em] text-[#9b968d]"><span>© 2026 AAAYAN Immunotech LLP</span><span>Privacy · Terms</span></div></footer>; }
